'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

/**
 * ZigBeeDoubleSocketDriver – base class for all Zigbee double socket drivers.
 *
 * Registers the Socket 2 flow card listeners generated by the Homey Compose
 * system from each driver's driver.flow.compose.json.
 *
 * Card IDs are prefixed with the driver id (underscores → hyphens), e.g.
 * for aurora_aone the cards are aurora-aone_socket2_turn_on etc.
 */
class ZigBeeDoubleSocketDriver extends ZigBeeDriver {

  /**
   * Return the compose-generated card ID prefix for this driver.
   * e.g. aurora_aone → "aurora-aone"
   */
  get _cardPrefix() {
    return this.manifest.id.replace(/_/g, '-');
  }

  async onInit() {
    await super.onInit();

    const prefix = this._cardPrefix;

    // ── Socket 1 ──────────────────────────────────────────────────────────

    // Device trigger cards
    this._socket1TurnedOnCard = this.homey.flow.getDeviceTriggerCard(`${prefix}_socket1_turned_on`);
    this._socket1TurnedOffCard = this.homey.flow.getDeviceTriggerCard(`${prefix}_socket1_turned_off`);

    // Condition
    this.homey.flow.getConditionCard(`${prefix}_socket1_is_on`)
      .registerRunListener(async (args) => {
        return args.device.getCapabilityValue('onoff') === true;
      });

    // Actions
    this.homey.flow.getActionCard(`${prefix}_socket1_turn_on`)
      .registerRunListener(async (args) => {
        await args.device.triggerCapabilityListener('onoff', true);
      });

    this.homey.flow.getActionCard(`${prefix}_socket1_turn_off`)
      .registerRunListener(async (args) => {
        await args.device.triggerCapabilityListener('onoff', false);
      });

    this.homey.flow.getActionCard(`${prefix}_socket1_toggle`)
      .registerRunListener(async (args) => {
        const current = args.device.getCapabilityValue('onoff');
        await args.device.triggerCapabilityListener('onoff', !current);
      });

    // ── Socket 2 ──────────────────────────────────────────────────────────

    // Device trigger cards
    this._socket2TurnedOnCard = this.homey.flow.getDeviceTriggerCard(`${prefix}_socket2_turned_on`);
    this._socket2TurnedOffCard = this.homey.flow.getDeviceTriggerCard(`${prefix}_socket2_turned_off`);

    // Condition
    this.homey.flow.getConditionCard(`${prefix}_socket2_is_on`)
      .registerRunListener(async (args) => {
        return args.device.getCapabilityValue('onoff.socket2') === true;
      });

    // Actions
    this.homey.flow.getActionCard(`${prefix}_socket2_turn_on`)
      .registerRunListener(async (args) => {
        await args.device.triggerCapabilityListener('onoff.socket2', true);
      });

    this.homey.flow.getActionCard(`${prefix}_socket2_turn_off`)
      .registerRunListener(async (args) => {
        await args.device.triggerCapabilityListener('onoff.socket2', false);
      });

    this.homey.flow.getActionCard(`${prefix}_socket2_toggle`)
      .registerRunListener(async (args) => {
        const current = args.device.getCapabilityValue('onoff.socket2');
        await args.device.triggerCapabilityListener('onoff.socket2', !current);
      });
  }

  /**
   * Called by ZigBeeDoubleSocketDevice when a socket's on/off state changes.
   * @param {Homey.Device} device
   * @param {number} socket - 1 or 2
   * @param {boolean} isOn
   */
  triggerSocket(device, socket, isOn) {
    let card;
    if (socket === 1) {
      card = isOn ? this._socket1TurnedOnCard : this._socket1TurnedOffCard;
    } else {
      card = isOn ? this._socket2TurnedOnCard : this._socket2TurnedOffCard;
    }
    if (card) {
      card.trigger(device, {}, {}).catch(this.error);
    }
  }

}

module.exports = ZigBeeDoubleSocketDriver;
